version: '3.6'
services:

  database:
    image: postgres:11
    container_name: database
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - backend
#    volumes:
#      - ./pg_data/data:${PGDATA:-/var/lib/postgresql/data}
#      - ./pg_data/logs:${POSTGRES_INITDB_WALDIR:-/var/log/postgresql}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=postgres

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    image: django
    container_name: django
    depends_on:
      - database
    ports:
      - 8000:8000
    networks:
      - frontend
      - backend
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
    environment:
      - UWSGI_UID=${UWSGI_UID:-1000}
      - UWSGI_GID=${UWSGI_GID:-1000}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
      - 8443:443
    networks:
      - frontend
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_SSL_CERT:-./certs/self.signed.crt}:/etc/ssl/SSL.crt:ro
      - ${NGINX_SSL_KEY:-./certs/self.signed.key}:/etc/ssl/SSL.key:ro

networks:
  frontend:
  backend: